### ISSUE TITLE
Resolved #987 - Add glfwDragWindow function to latest platform structure

### ISSUE THREAD

**Issue by bjorndm** [bjorndm/glfwff#8]
https://github.com/glfw/glfw/pull/2152: Useful feature, implemented on all platforms.

**Comment by ws909** [comment]
> implemented on all platforms.

Not true. It is not implemented on MacOS. 

I noticed that you forked GLFW because you're unhappy with the speed of development, and that PRs seem to linger without being merged. While I agree with you that GLFW development can be painfully slow, and that PRs should be merged faster, there's usually a reason why certain important additions to GLFW don't get merged for so many years. In this case, it's because there is no implementation on MacOS, and it's neither easy to add one. I looked into this a slight bit, as it's a feature I'm also interested in, but I couldn't find a solution for MacOS in the time that I had available. So, you merged a PR on the incorrect basis that it provided an implementation for all platforms. 

You should not rely on this feature if you want cross-platform coverage. If you do choose to rely on it, you will not be able to extend it to work on MacOS in the future, simply because the API likely must look different.

**Comment by bjorndm** [comment]
In that case, please help out and provide the macos port of this function. It is ok if the api changes, no one except me uses this fork anyway, and I made it for my own use, mostly. The fact that something isn't implemented on all platforms doesn't mean we should wait for years. It means we should choose a likely experimental API and implement it step by step. It you have the time to come and comment here, you should have time enough to help out as wel...

**Comment by ws909** [comment]
Eh, you clearly underestimate the amount of work it takes to fix that issue. Nobody was able to fix it for so long, but you expect me to sit down and get it done? Cocoa doesn’t even seem to have any kind of API for this. If we venture into the land of private APIs to get it fixed, we’re bound to have GLFW break, and no programs using GLFW will be accepted into the App Store. 

> no one except me uses this fork anyway

You advertised it multiple places, changed the description of the project, and got a star from someone.

**Comment by bjorndm** [comment]
I expect you to walk the walk if you talk the talk.  But thanks anyway for letting me know it actually doesn't work on Cocoa. I will document this in the source code.

If this cannot work at all on Cocoa, then it is enough to document this and pass on to the next feature. Not every API has to do something useful on all platforms, if the platform cannot do it it is OK to leave it a no op for that platform, or as I said before, adopt the API and see if some implementation materializes after all. I don't agree with the idea of waiting for years just for one platform implementation.

As for advertising... That's just how GitHub works if you refer issues.

**Comment by bjorndm** [comment]
See #19
